dir2=$(pwd)
#python articulation.py "/home/camilo/Camilo/UdeA/data/PCGITA/readtext/" "articulation_PD_readtextDyn.txt" "dynamic" "false" "false"
#python articulation.py "/home/camilo/Camilo/UdeA/data/PCGITA/monologue/" "articulation_PD_monologueDyn.txt" "dynamic" "false" "false"
#python articulation.py "/home/camilo/Camilo/UdeA/data/PCGITA/pataka/" "articulation_PD_DDKDyn.txt" "dynamic" "false" "false"
python articulation.py "/home/camilo/Camilo/UdeA/data/PCGITA/sent01/" "articulation_PD_sent01Dyn.txt" "dynamic" "false" "false"
python articulation.py "/home/camilo/Camilo/UdeA/data/PCGITA/sent02/" "articulation_PD_sent02Dyn.txt" "dynamic" "false" "false"
python articulation.py "/home/camilo/Camilo/UdeA/data/PCGITA/sent03/" "articulation_PD_sent03Dyn.txt" "dynamic" "false" "false"
python articulation.py "/home/camilo/Camilo/UdeA/data/PCGITA/sent04/" "articulation_PD_sent04Dyn.txt" "dynamic" "false" "false"
python articulation.py "/home/camilo/Camilo/UdeA/data/PCGITA/sent05/" "articulation_PD_sent05Dyn.txt" "dynamic" "false" "false"
python articulation.py "/home/camilo/Camilo/UdeA/data/PCGITA/sent06/" "articulation_PD_sent06Dyn.txt" "dynamic" "false" "false"
python articulation.py "/home/camilo/Camilo/UdeA/data/PCGITA/sent07/" "articulation_PD_sent07Dyn.txt" "dynamic" "false" "false"
python articulation.py "/home/camilo/Camilo/UdeA/data/PCGITA/sent08/" "articulation_PD_sent08Dyn.txt" "dynamic" "false" "false"
python articulation.py "/home/camilo/Camilo/UdeA/data/PCGITA/sent09/" "articulation_PD_sent09Dyn.txt" "dynamic" "false" "false"
python articulation.py "/home/camilo/Camilo/UdeA/data/PCGITA/sent10/" "articulation_PD_sent10Dyn.txt" "dynamic" "false" "false"
